@startuml Сокращатель ссылок, диаграмма последовательности
"Отправитель SMS" -> Сокращатель: Ссылка для сокращения
Сокращатель -> "Отправитель SMS": Короткая ссылка

"Отправитель SMS" --> Клиент: SMS с короткой ссылкой

Клиент -> Сокращатель: Короткая ссылка
Клиент <- Сокращатель: длинная ссылка
@enduml

@startuml Сокращатель ссылок, API
"Отправитель SMS" -> Сокращатель: POST, JSON\n{"link": "ссылка для сокращения"}
Сокращатель -> "Отправитель SMS": JSON,\n{"shortUrl": "короткая ссылка"}

Клиент -> Сокращатель: Короткая ссылка
Клиент <- Сокращатель: HTTP, 302,\nLocation: "длинная ссылка"
@enduml

@startuml Сокращатель ссылок, c1

node app
cloud sender
actor Client

database database

app -> database

sender -> app

Client -> app

@enduml